- name: meu primeiro exercicio
  hosts: all
  tasks: 
   - name: instalando pacotes
     package: 
      name:
       - vim
       - htop
       - cowsay
       - sl

   - name: adicionando usuarios
     user:
      name: "{{item}}"
      shell: '/bin/bash'
      password: '$1$f35WDxET$ltJmpYWPV/ZSBvdZmcncR.'
     with_items:
      - devops
      - developer
      - roliveira

- name: instalando somente o epel-release
  hosts: "{{host}}"
  vars:
   - host: automation
  tasks:
   - name: instalando o epel-release
     package:
      name: epel-release






