- name: instalando gitlab

  hosts: devops
  
  tasks: 
  
   - name: instalando dependencias
     package: 
      name: 
       - curl 
       - openssh-server 
       - ca-certificates
       - postfix
      state: present

   - name: adicionando o repositorio
     shell: "curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | /bin/bash"

   - name: instalando gitlab-ce
     package: 
      name: gitlab-ce 
      state: present
      update_cache: yes

